version: '3.0'

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./clien/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
        - '4200:4200'
        - '49153:49153'
