version: '3.0'

services:
  client:
    container_name: client
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
        - '3000:80'
  server:
    container_name: server
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - '/tmp'
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - '8080:8080'

  postgres:
    container_name: postgres
    build: 
      context: ./server/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=app
    ports:
      - "5432:5432"