version: '3.0'

services:
  example:
    container_name: example
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
        - '4200:4200'
        - '49153:49153'
